#CI项目名
name: Immortal

on:
  #自动编译：每周五早上6点
  schedule:
    - cron: 0 22 * * 4
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  Upsing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Update sing-box version
        run: |
          chmod +x ./Scripts/Upsing.sh
          ./Scripts/Upsing.sh

      - name: Commit changes
        id: commit-changes
        run: |
          if [ -n "$(git status --porcelain ./Scripts/Packages.sh)" ]; then
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update sing-box version"
          echo "singupdated=true" >> $GITHUB_OUTPUT
          else
            echo "No sing update"
          fi     
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ steps.commit-changes.outputs.singupdated == 'true' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}       
