#CI项目名
name: Mediatek-Lede

on:
  #在前置准备完成后运行
  workflow_run:
    workflows: ["#Immortal#"]
    types:
      - completed

#CI权限
permissions: write-all

#CI任务
jobs:
  wrt_config:
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: Mediatek
      #默认主题
      WRT_THEME: design
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名
      WRT_WIFI: OWRT
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #默认地址
      WRT_IP: 192.168.10.1
      #默认源码
      WRT_URL: https://github.com/coolsnowwolf/lede.git
      #默认分支
      WRT_BRANCH: master
