#CI项目名
name: Mediatek-Immortal

on:
  #自动编译：每周五早上6点
  schedule:
    - cron: 0 22 * * 4
  #手动编译
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
        description: 'Version of jq to install'
        default: '1.7.1'

#CI权限
permissions: write-all

#CI任务
jobs:
  Upsing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main
        
      - name: Install jq              
        uses: dcarbone/install-jq-action@v2.1.0
        with:
          version: '${{ inputs.version }}'

      - name: Update sing-box version
        run: ./Scripts/Upsing.sh

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update sing-box version"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


  wrt_config:
    needs: Upsing
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: Mediatek
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名
      WRT_WIFI: OWRT
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #默认地址
      WRT_IP: 192.168.10.1
      #默认源码
      WRT_URL: https://github.com/immortalwrt/ImmortalWrt.git
      #默认分支
      WRT_BRANCH: master
